name: Build Kernel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        swap-size-mb: 10240

    - name: Checkout main repository
      uses: actions/checkout@v4.1.7
      with:
        repository: mylove90/sm-a245f_14_opensource

    - name: Sync kernel source
      run: |
        git clone --depth=1 -b a245f https://github.com/mylove90/Samsung_Mt6789_Kernel kernel-5.10/

    - name: Sync toolchains from GitLab
      run: |
        git clone --depth=1 -b A155F/N https://gitlab.com/mylove90/toolchain.git toolchain
        cd toolchain
        cp -r * ../

    - name: Sync Anykernel3
      run: |
        git clone --depth=1 --branch A15 https://github.com/mylove90/AnyKernel3 AnyKernel3

    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev
        sudo apt install -y curl git ftp lftp wget libarchive-tools ccache python2 python2-dev
        sudo apt install -y zip unzip tar gzip bzip2 rar unrar

    - name: Build kernel
      run: |
        chmod a+x build_kernel.sh
        bash build_kernel.sh

    - name: Pack AnyKernel3 ZIP
      run: |
        cp -f out/target/product/a24/obj/KERNEL_OBJ/kernel-5.10/arch/arm64/boot/Image.gz ./AnyKernel3/
        cd AnyKernel3/
        rm -rf .git .github README.md
        zip -r9 a245f-kernel.zip *

    - name: Upload AnyKernel3 ZIP
      uses: actions/upload-artifact@v4.3.4
      with:
        name: a245f-kernel.zip
        path: AnyKernel3/a245f-kernel.zip
